Browser("British American Tobacco").Page("British American Tobacco").Link("UnsereProdukte").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco").Link("UnsereProdukte")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_2").Link("Rohstoff Tabak").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 2").Link("Rohstoff Tabak")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_3").Link("Verbraucherund Handel").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 3").Link("Verbraucherund Handel")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_4").Link("Werbung").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 4").Link("Werbung")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_5").Link("Gesundheit undWissenschaft").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 5").Link("Gesundheit undWissenschaft")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_6").Link("Verantwortung").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 6").Link("Verantwortung")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_7").Link("Nachhaltigkeitsmanagement").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 7").Link("Nachhaltigkeitsmanagement")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_8").Link("Karriere").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 8").Link("Karriere")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("British American Tobacco").Page("British American Tobacco_9").Image("Einstiegsmöglichkeiten").Click @@ hightlight id_;_Browser("British American Tobacco").Page("British American Tobacco 9").Image("Einstiegsmöglichkeiten")_;_script infofile_;_ZIP::ssf9.xml_;_
